apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleservice
  labels:
    app: simpleservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simpleservice
  template:
    metadata:
      name: simpleservice
      labels:
        app: simpleservice
    spec:
      containers:
        - name: simple-webservice
          image: {{ .Values.simpleservice.image.repository}}:{{ .Values.simpleservice.image.tag }}
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
