apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.simpleservice.app.name }}
  labels:
    app: {{ .Values.simpleservice.app.name }}
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.simpleservice.app.name }}
