apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleservice
  labels:
    app: simpleservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simpleservice
  template:
    metadata:
      name: simpleservice
      labels:
        app: simpleservice
    spec:
      containers:
        - name: simpleservice
          image: {{ .Values.simpleservice.image.repository }}:{{ .Values.simpleservice.image.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
      restartPolicy: Always
